# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "3.x" ]
  pull_request:
    branches: [ "3.x" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: '1.8'
        cache: maven
    - name: Build with Maven
      run: mvn clean install -DskipTests
    - name: Deploy to Tomcat
      run: curl -v -u secret_TOMCAT_USERNAME:secret_TOMCAT_PASSWORD -T '/home/runner/work/openmrs-module-ugandaemr/omod/target/docker/web/openmrs.war' 'https://ugandaemr-backend.mets.or.ug/manager/text/deploy?path=openmrs'
